name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cmd /c build.bat 
      
    - uses: actions/upload-artifact@v2
      name: Upload
      with:
        name: Examples
        path: bin
